name: Quality Check

on:
  pull_request:
    branches: [dev, main]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, xml

      - name: Install dependencies
        run: |
          composer install

      - name: Create .env file
        run: |
          cp .env.example .env || echo "APP_KEY=base64:$(php artisan key:generate --show)" > .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse --level=max

      - name: Run PHP_CodeSniffer
        run: |
          vendor/bin/phpcs --standard=PSR12 app/

      - name: Run Pest tests
        run: |
          vendor/bin/pest --configuration phpunit.xml

      - name: Check for Composer security issues
        run: |
          vendor/bin/composer audit
