<?php

declare(strict_types=1);

namespace App\Domain\Enums;

enum TankHistoryEvent: string
{
    case CLEANING    = 'cleaning';
    case MAINTENANCE = 'maintenance';
    case FALLOWING   = 'fallowing';
    /** Automatically generated by TankObserver when the status column changes. */
    case STATUS_CHANGE = 'status_change';

    public function label(): string
    {
        return match ($this) {
            self::CLEANING      => 'Limpeza',
            self::MAINTENANCE   => 'Manutenção',
            self::FALLOWING     => 'Pousio',
            self::STATUS_CHANGE => 'Mudança de Status',
        };
    }

    /** Events that place the tank in an unavailable state for new stockings. */
    public function blocksNewAllocations(): bool
    {
        return match ($this) {
            self::CLEANING, self::MAINTENANCE, self::FALLOWING => true,
            self::STATUS_CHANGE => false,
        };
    }
}
